language: node_js
node_js:
  - 'node'

script:
  - npm start &
  - sleep 10
  - npx jest browser-test/browserstack.test.js

addons:
  browserstack:
    username: eemeliaro2
    access_key:
      secure: 'nKqoVF/PAVPoBcg5yJdeW4Txw8IZRAzWdVq+YCG/FL2f8ihbFg6pm5c77vsiSXfZN1kRI3lk8aqtN2a0yEKUn/8Y6K2glhFQpIEh3xGnKCwmEU/FMhul/Y29EUB6FjUorx1aO0sEL52H6C1i6UeKPTbKrV5fBYrO8YX9cdEIjXMGVU3Wv11rhn/qj/tzkDWNSY+BUrcg8bQcBiYdcYnUwI2s2iTdTr9WxyhSVY9opXluQcotf99B/jM733Wz6obhHkUM7fL3PXDKmWWQzU70XA0BhxJZaPHfayi3o/3P5+ZL116Yfn86QZmzR84bRcFQ/hMB92yEtL6BNPaQ9zQr+gDTLHUjo6nEaAQk3d/OuDtmtEsU7erZCEi+j9dfd7j+kjf6XjdwzoJ17rqfmqkbbs2ijrf8z8U8Ax3INt2XBWUazLlyyO0Ak0/CLU2hqBClAh1rlRJ3hc7XwWDBcKHpcovdUHUZn4hutYhzn0P4HAoN7rAP5TW9G7CZBCxTaMFLmgNGwHwXdxtWtpoW/Df0HkWW5iY4dtcGIbgEzmafsjLWFpRTMuvPSB6ez7JuyrEHl1UlJ3zAm2zEquIuo3S2agoYV/xgjOE5RVYTkL4S7H5EKryqcP64quL9hQhqeYkcjt5eiWk9lEEx1uXzKQlDqQKHR762uGeFNCMzuFbtUMA='
