name: Update Pages

on:
  - workflow_dispatch

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/checkout@v4
        with:
          repository: eemeli/yaml
          submodules: true
      - run: npm ci
      - run: npm run build:browser
      - name: Playground setup
        working-directory: ./playground
        run: npm ci
      - name: Playground build
        working-directory: ./playground
        run: npm run build

      - uses: actions/checkout@v4
        with:
          repository: eemeli/yaml-playground
          ref: gh-pages
          path: ./gh-pages
      - run: rm gh-pages/*
      - run: cp playground/site/* gh-pages/

      - name: git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add . && git commit -m 'Update playground' && git push
        working-directory: ./gh-pages
